### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by Guest007** [exebook/x11clipboard#1]
Делал всё по инструкции deodar, но получаю ошибку:

$ node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.0
gyp info using node@0.10.26 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/guest007/tmp/test/deodar/x11clip/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/guest007/.node-gyp/0.10.26/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/guest007/.node-gyp/0.10.26',
gyp info spawn args   '-Dmodule_root_dir=/home/guest007/tmp/test/deodar/x11clip',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.11.0-19-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/guest007/tmp/test/deodar/x11clip
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 

Из-за чего? Что делать? Очень хочется посмотреть...

**Comment by exebook** [comment]
говорят, что именно в таком случае вот этот комент помогает:

https://github.com/TooTallNate/node-gyp/issues/363#issuecomment-33212812

кажется, это связано с путаницей с несоклькими питонами одновремено установлеными в системе

**Comment by exebook** [comment]
not related to this repo
